"""empty message

Revision ID: 140e99ffdcee
Revises: c803a7edde66
Create Date: 2020-04-11 11:20:08.803562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '140e99ffdcee'
down_revision = 'c803a7edde66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'prefered_hours',
               existing_type=postgresql.ENUM('morning', 'afternoon', 'evening', name='missionpreferedhours'),
               nullable=True)
    op.alter_column('missions', 'scheduled_to_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index('ix_missions_scheduled_to_date', table_name='missions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_missions_scheduled_to_date', 'missions', ['scheduled_to_date'], unique=False)
    op.alter_column('missions', 'scheduled_to_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('missions', 'prefered_hours',
               existing_type=postgresql.ENUM('morning', 'afternoon', 'evening', name='missionpreferedhours'),
               nullable=False)
    # ### end Alembic commands ###
