"""Add owner_id to Mission (FK to Volunteer)

Revision ID: 227395345c6b
Revises: 2b11c057ee9b
Create Date: 2020-04-24 17:28:52.233300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227395345c6b'
down_revision = 'ba396e16f426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'missions', 'volunteers', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'missions', type_='foreignkey')
    op.drop_column('missions', 'owner_id')
    # ### end Alembic commands ###
