"""adding state declined on VolunterMissionState

Revision ID: 2b11c057ee9b
Revises: febc57ad8930
Create Date: 2020-04-16 20:14:22.374291

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '2b11c057ee9b'
down_revision = 'febc57ad8930'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("COMMIT")
    op.execute("ALTER TYPE volunteermissionstate ADD VALUE 'declined' AFTER 'accepted'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
