"""empty message

Revision ID: 34f027be92a2
Revises: 
Create Date: 2020-04-10 13:22:09.215394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34f027be92a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('elder_first_name', sa.String(), nullable=True),
    sa.Column('elder_last_name', sa.String(), nullable=True),
    sa.Column('elder_phone_number', sa.String(), nullable=True),
    sa.Column('elder_address_lat', sa.Float(), nullable=False),
    sa.Column('elder_address_lng', sa.Float(), nullable=False),
    sa.Column('elder_address_str', sa.Text(), nullable=True),
    sa.Column('scheduled_to_date', sa.Date(), nullable=False),
    sa.Column('prefered_hours', sa.Enum('morning', 'afternoon', 'evening', name='missionpreferedhours'), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'bank_transfer', 'check', 'no_payment', name='missionpaymentmethod'), nullable=False),
    sa.Column('error_state', sa.Enum('no_one_answered_call', 'not_relevant_anymore', 'no_volunteers_found', name='missionerrorstate'), nullable=True),
    sa.Column('additional_contact_name', sa.String(), nullable=True),
    sa.Column('additional_contact_phone', sa.String(), nullable=True),
    sa.Column('additional_contact_role', sa.Enum('doctor', 'family', 'other', name='missionadditionalcontactrole'), nullable=True),
    sa.Column('use_additional_contact', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'approved', 'acquired', 'started', 'completed', 'canceled', 'error', name='missionstate'), nullable=True),
    sa.Column('pickup_point', sa.Text(), nullable=False),
    sa.Column('is_elder_need_visit_before', sa.Enum('yes', 'no', 'unknown', name='missioniselderneedvisitbefore'), nullable=True),
    sa.Column('purpose', sa.Enum('grocery', 'pharmacy', 'grocery_and_pharmacy', 'general', name='missionpurpose'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_missions_additional_contact_phone'), 'missions', ['additional_contact_phone'], unique=False)
    op.create_index(op.f('ix_missions_elder_address_lat'), 'missions', ['elder_address_lat'], unique=False)
    op.create_index(op.f('ix_missions_elder_address_lng'), 'missions', ['elder_address_lng'], unique=False)
    op.create_index(op.f('ix_missions_elder_phone_number'), 'missions', ['elder_phone_number'], unique=True)
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_index(op.f('ix_missions_purpose'), 'missions', ['purpose'], unique=False)
    op.create_index(op.f('ix_missions_scheduled_to_date'), 'missions', ['scheduled_to_date'], unique=False)
    op.create_index(op.f('ix_missions_state'), 'missions', ['state'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('otp_code', sa.String(), nullable=True),
    sa.Column('attempts_left', sa.Integer(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_phone_number'), 'otp_verifications', ['phone_number'], unique=True)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_description', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_completed_at'), 'scheduled_tasks', ['completed_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_created_at'), 'scheduled_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_endpoint'), 'scheduled_tasks', ['endpoint'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_executed_at'), 'scheduled_tasks', ['executed_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_failed_at'), 'scheduled_tasks', ['failed_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_failure_description'), 'scheduled_tasks', ['failure_description'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_id'), 'scheduled_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_scheduled_at'), 'scheduled_tasks', ['scheduled_at'], unique=False)
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('user', 'coordinator', 'call_center', 'support', 'admin', name='volunteerrole'), nullable=True),
    sa.Column('address_lat', sa.Float(), nullable=False),
    sa.Column('address_lng', sa.Float(), nullable=False),
    sa.Column('address_str', sa.Text(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.Column('last_whatsapp_welcome', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_volunteers_address_lat'), 'volunteers', ['address_lat'], unique=False)
    op.create_index(op.f('ix_volunteers_address_lng'), 'volunteers', ['address_lng'], unique=False)
    op.create_index(op.f('ix_volunteers_email'), 'volunteers', ['email'], unique=True)
    op.create_index(op.f('ix_volunteers_id'), 'volunteers', ['id'], unique=False)
    op.create_index(op.f('ix_volunteers_phone_number'), 'volunteers', ['phone_number'], unique=True)
    op.create_index(op.f('ix_volunteers_role'), 'volunteers', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteers_role'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_phone_number'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_id'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_email'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_address_lng'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_address_lat'), table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_index(op.f('ix_scheduled_tasks_scheduled_at'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_failure_description'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_failed_at'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_executed_at'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_endpoint'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_created_at'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_completed_at'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_otp_verifications_phone_number'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_missions_state'), table_name='missions')
    op.drop_index(op.f('ix_missions_scheduled_to_date'), table_name='missions')
    op.drop_index(op.f('ix_missions_purpose'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_elder_phone_number'), table_name='missions')
    op.drop_index(op.f('ix_missions_elder_address_lng'), table_name='missions')
    op.drop_index(op.f('ix_missions_elder_address_lat'), table_name='missions')
    op.drop_index(op.f('ix_missions_additional_contact_phone'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
