"""empty message

Revision ID: a559679e6cab
Revises: 140e99ffdcee
Create Date: 2020-04-11 12:11:38.067639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a559679e6cab'
down_revision = '140e99ffdcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('additional_contact_email', sa.String(), nullable=True))
    op.drop_index('ix_missions_additional_contact_phone', table_name='missions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_missions_additional_contact_phone', 'missions', ['additional_contact_phone'], unique=False)
    op.drop_column('missions', 'additional_contact_email')
    # ### end Alembic commands ###
