"""mission pickup_point is nullable

Revision ID: ba396e16f426
Revises: 2b11c057ee9b
Create Date: 2020-04-24 12:22:51.549096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba396e16f426'
down_revision = '2b11c057ee9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'pickup_point',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'pickup_point',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
