"""empty message

Revision ID: c803a7edde66
Revises: c5c88c9e5ce5
Create Date: 2020-04-10 23:29:55.969952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c803a7edde66'
down_revision = 'c5c88c9e5ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_tasks_endpoint', table_name='scheduled_tasks')
    op.create_index(op.f('ix_scheduled_tasks_endpoint'), 'scheduled_tasks', ['endpoint'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_tasks_endpoint'), table_name='scheduled_tasks')
    op.create_index('ix_scheduled_tasks_endpoint', 'scheduled_tasks', ['endpoint'], unique=False)
    # ### end Alembic commands ###
