"""empty message

Revision ID: f3fd2cf6022b
Revises: 34f027be92a2
Create Date: 2020-04-10 18:20:31.013635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fd2cf6022b'
down_revision = '34f027be92a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_mission',
    sa.Column('volunteer_id', sa.BigInteger(), nullable=False),
    sa.Column('mission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('volunteer_id', 'mission_id')
    )
    op.add_column('missions', sa.Column('state_changed_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_missions_elder_phone_number', table_name='missions')
    op.create_index(op.f('ix_missions_elder_phone_number'), 'missions', ['elder_phone_number'], unique=False)
    op.drop_constraint('volunteers_mission_id_fkey', 'volunteers', type_='foreignkey')
    op.drop_column('volunteers', 'mission_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers', sa.Column('mission_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('volunteers_mission_id_fkey', 'volunteers', 'missions', ['mission_id'], ['id'])
    op.drop_index(op.f('ix_missions_elder_phone_number'), table_name='missions')
    op.create_index('ix_missions_elder_phone_number', 'missions', ['elder_phone_number'], unique=True)
    op.drop_column('missions', 'state_changed_at')
    op.drop_table('volunteer_mission')
    # ### end Alembic commands ###
